# Generated by Django 4.2.1 on 2023-07-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_delete_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='applicantmodel',
            new_name='jobseeker_details',
        ),
        migrations.DeleteModel(
            name='profile1',
        ),
    ]
