# Generated by Django 4.2.1 on 2023-07-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='addjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=20)),
                ('work_type', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('job_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='profile1',
        ),
    ]
