# Generated by Django 4.2.1 on 2023-07-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_addjob_delete_profile1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='work_type',
            field=models.CharField(choices=[('h', 'hybrid'), ('r', 'rural'), ('c', 'city')], max_length=20),
        ),
    ]
