# Generated by Django 4.2.1 on 2023-07-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_alter_addjob_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='work_type',
            field=models.CharField(blank=True, choices=[('Rural', 'Rural')], max_length=10),
        ),
    ]
