# Generated by Django 4.2.1 on 2023-07-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0015_alter_addjob_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
