# Generated by Django 4.2.1 on 2023-07-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_alter_addjob_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='work_type',
            field=models.CharField(choices=[('hybrid', 'hybrid'), ('rural', 'rural'), ('city', 'city')], max_length=20),
        ),
    ]
