# Generated by Django 4.2.1 on 2023-07-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_alter_addjob_work_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='applied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=20)),
                ('phoneno', models.IntegerField()),
                ('experience', models.CharField(max_length=20)),
                ('uploadyourresume', models.FileField(upload_to='')),
            ],
        ),
    ]
