# Generated by Django 4.2.1 on 2023-07-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applied',
            old_name='companyname',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='applied',
            old_name='phoneno',
            new_name='phone_num',
        ),
        migrations.RenameField(
            model_name='applied',
            old_name='uploadyourresume',
            new_name='upload_resume',
        ),
    ]
