# Generated by Django 4.2.1 on 2023-07-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_alter_applied_upload_resume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobseeker_details',
            new_name='jobseeker',
        ),
    ]
